Update ssl-checker

diff --git a/.github/workflows/ssl-checker b/.github/workflows/ssl-checker
--- a/.github/workflows/ssl-checker
+++ b/.github/workflows/ssl-checker
@@ -1,59 +1,90 @@
-#!/bin/bash
+name: Check domains
+env:
+  DAYS_TO_EXPIRE_CRIT: 100
 
-# @HoangDH - Jun 29 2019
-# set -ex
+on:
+  schedule:
+    - cron:  '*/60 * * * *'
+  push:
+    branches: [ main ]
+  workflow_dispatch:
 
-notify() {
-  WEBHOOK=""
-  SLACK_CHANNEL="#ssl-monitor"
-  SLACK_TEXT="Domain $1 issued by $4 will expire in $2"
-  SLACK_BOTNAME="SSL Checker"
+jobs:
+  Check-ssl-for-domain:
+    runs-on: ubuntu-latest
+    name: Check domain
+    strategy:
+      matrix:
+        domain:
+          - https://oli.sh
+          - https://editorjs.io
+          - https://www.amaysim.com.au
+          - https://oliwiak.com
+          - https://www.vaya.net.au
+          - https://olii.sh
+          - https://oliwiakk.com
 
-  DOMAIN="$1"
-  EXPIRY_DAYS="$2"
-  EXPIRY_DATE="$3"
-  ISSUER="$4"
-  COLOR="$5"
+    steps:
 
-  SLACK_PAYLOAD="payload={\"channel\":\"${SLACK_CHANNEL}\",\"text\":\"${SLACK_TEXT}\",\"icon_emoji\":\":skull:\",\"username\":\"${SLACK_BOTNAME}\",\"attachments\":[{\"color\":\"${COLOR}\",\"fields\":[{\"title\":\"Domain:\",\"value\":\"${DOMAIN}\",\"short\":true},{\"title\":\"Expiry day(s):\",\"value\":\"${EXPIRY_DAYS}\",\"short\":true},{\"title\":\"Expiry date:\",\"value\":\"$EXPIRY_DATE\",\"short\":true},{\"title\":\"Issued by:\",\"value\":\"$ISSUER\",\"short\":true}]}]}"
-  #echo $SLACK_PAYLOAD
-  curl -s -o /dev/null -X POST --data-urlencode "$SLACK_PAYLOAD" $WEBHOOK
-  #echo ""
-  echo "Slack notification sent"
-}
 
-check_certs() {
-  if [ -z "$1" ]
-  then
-    echo "Domain name missing"
-    exit 1
-  fi
-  name="$1"
-  shift
+      - name: Check SSL
+        id: check-domain
+        with:
+          url: ${{ matrix.domain }}
+        run: |
+          echo '${{ matrix.domain }}'
+          notify() {
+            WEBHOOK=""
+            SLACK_CHANNEL="#ssl-monitor"
+            SLACK_TEXT="Domain $1 issued by $4 will expire in $2"
+            SLACK_BOTNAME="SSL Checker"
 
-  now_epoch=$( date +%s )
-  ip_server=$(dig +short a $name)
-  dig +noall +answer +short $name | while read -r ip;
-  do
-    if [ "$ip" == "$ip_server" ]
-    then
-      data=`echo | openssl s_client -showcerts -servername $name -connect $ip:443 2>/dev/null | openssl x509 -noout -enddate -issuer`
-      expiry_date=$(echo $data | grep -Eo "notAfter=(.*)GMT" | cut -d "=" -f 2)
-      #issuer=$(echo $data | grep -Eo "CN=(.*)"| cut -d "=" -f 2)
-      issuer=$(echo $data | awk 'BEGIN {RS=", " } $0 ~ /^O =/ { print substr($0,5,17)}'|sed 's/"//g')
-      expiry_epoch=$(date -d "$expiry_date" +%s)
-      expiry_days="$(( ($expiry_epoch - $now_epoch) / (3600 * 24) ))"
-      if [ $expiry_days -lt 30 ]
-      then
-          color="#ff0000"
-          notify "$name" "$expiry_days" "$expiry_date" "$issuer" "$color"
-      else
-          color="#2eb886"
-          #notify "$name" "$expiry_days" "$expiry_date" "$issuer" "$color"
-          echo "All good, let's don't spam slack"
-      fi
-    fi
-  done
-}
+            DOMAIN="$1"
+            EXPIRY_DAYS="$2"
+            EXPIRY_DATE="$3"
+            ISSUER="$4"
+            COLOR="$5"
 
-check_certs $1
+            SLACK_PAYLOAD="payload={\"channel\":\"${SLACK_CHANNEL}\",\"text\":\"${SLACK_TEXT}\",\"icon_emoji\":\":skull:\",\"username\":\"${SLACK_BOTNAME}\",\"attachments\":[{\"color\":\"${COLOR}\",\"fields\":[{\"title\":\"Domain:\",\"value\":\"${DOMAIN}\",\"short\":true},{\"title\":\"Expiry day(s):\",\"value\":\"${EXPIRY_DAYS}\",\"short\":true},{\"title\":\"Expiry date:\",\"value\":\"$EXPIRY_DATE\",\"short\":true},{\"title\":\"Issued by:\",\"value\":\"$ISSUER\",\"short\":true}]}]}"
+            #echo $SLACK_PAYLOAD
+            curl -s -o /dev/null -X POST --data-urlencode "$SLACK_PAYLOAD" $WEBHOOK
+            #echo ""
+            echo "Slack notification sent"
+          }
+
+          check_certs() {
+            if [ -z "$1" ]
+            then
+              echo "Domain name missing"
+              exit 1
+            fi
+            name="$1"
+            shift
+
+            now_epoch=$( date +%s )
+            ip_server=$(dig +short a $name)
+            dig +noall +answer +short $name | while read -r ip;
+            do
+              if [ "$ip" == "$ip_server" ]
+              then
+                data=`echo | openssl s_client -showcerts -servername $name -connect $ip:443 2>/dev/null | openssl x509 -noout -enddate -issuer`
+                expiry_date=$(echo $data | grep -Eo "notAfter=(.*)GMT" | cut -d "=" -f 2)
+                #issuer=$(echo $data | grep -Eo "CN=(.*)"| cut -d "=" -f 2)
+                issuer=$(echo $data | awk 'BEGIN {RS=", " } $0 ~ /^O =/ { print substr($0,5,17)}'|sed 's/"//g')
+                expiry_epoch=$(date -d "$expiry_date" +%s)
+                expiry_days="$(( ($expiry_epoch - $now_epoch) / (3600 * 24) ))"
+                if [ $expiry_days -lt 30 ]
+                then
+                    color="#ff0000"
+                    notify "$name" "$expiry_days" "$expiry_date" "$issuer" "$color"
+                else
+                    color="#2eb886"
+                    #notify "$name" "$expiry_days" "$expiry_date" "$issuer" "$color"
+                    echo "All good, let's don't spam slack"
+                fi
+              fi
+            done
+          }
+
+          check_certs $1
+
